version: "3"

services:
  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
  redis:
    image: redis:6.0.10-alpine
    ports:
      - 6379:6379
    volumes:
      - ./redisData:/data
      - ./redis.conf:/etc/redis/redis.conf

volumes:
  postgres:
